# Type stubs for dionaea.core (Cython module defined in binding.pyx)

from typing import Any

class dionaea:
    """Global dionaea instance providing configuration and system info."""
    def config(self) -> dict[str, Any]: ...
    def getifaddrs(self) -> dict[str, Any]: ...
    def version(self) -> str: ...

g_dionaea: dionaea

class node_info:
    """Node information storing address details."""
    @property
    def host(self) -> str: ...
    @host.setter
    def host(self, addr: str) -> None: ...
    @property
    def hostname(self) -> str: ...
    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, port: int) -> None: ...

class connection_speed:
    """Connection speed/throttle information."""
    @property
    def limit(self) -> float: ...
    @limit.setter
    def limit(self, limit: float) -> None: ...
    @property
    def bps(self) -> float: ...

class connection_accounting:
    """Connection accounting information."""
    @property
    def limit(self) -> float: ...
    @limit.setter
    def limit(self, limit: float) -> None: ...
    @property
    def bytes(self) -> float: ...

class connection_stats:
    """Connection statistics."""
    @property
    def speed(self) -> connection_speed: ...
    @property
    def accounting(self) -> connection_accounting: ...

class connection_timeouts:
    """Connection timeout settings."""
    @property
    def idle(self) -> float: ...
    @idle.setter
    def idle(self, timeout: float) -> None: ...
    @property
    def connecting(self) -> float: ...
    @connecting.setter
    def connecting(self, timeout: float) -> None: ...
    @property
    def listen(self) -> float: ...
    @listen.setter
    def listen(self, timeout: float) -> None: ...
    @property
    def reconnect(self) -> float: ...
    @reconnect.setter
    def reconnect(self, timeout: float) -> None: ...
    @property
    def handshake(self) -> float: ...
    @handshake.setter
    def handshake(self, timeout: float) -> None: ...
    @property
    def sustain(self) -> float: ...
    @sustain.setter
    def sustain(self, timeout: float) -> None: ...

class connection:
    """Network connection base class."""

    # Instance attributes that subclasses commonly use
    bistream: list[tuple[str, bytes]]

    def __init__(self, con_type: str | None = None) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: connection) -> bool: ...
    def __le__(self, other: connection) -> bool: ...
    def __gt__(self, other: connection) -> bool: ...
    def __ge__(self, other: connection) -> bool: ...

    def apply_config(self, config: dict[str, Any] | None) -> None: ...
    def apply_parent_config(self, parent: connection) -> None: ...
    def handle_established(self) -> None: ...
    def handle_disconnect(self) -> bool | int | None: ...
    def handle_origin(self, parent: connection) -> None: ...
    def handle_timeout_sustain(self) -> bool: ...
    def handle_timeout_idle(self) -> bool: ...
    def handle_timeout_listen(self) -> bool: ...
    def handle_error(self, err: int) -> None: ...
    def handle_io_in(self, data: bytes) -> int: ...
    def handle_io_out(self) -> None: ...

    def ref(self) -> int: ...
    def unref(self) -> int: ...
    def bind(self, addr: str, port: int, iface: str | None = ...) -> int: ...
    def listen(self, size: int = ...) -> int: ...
    def connect(self, addr: str, port: int, iface: str = ...) -> None: ...
    def send(self, data: bytes | str, local: tuple[str, int] | None = ..., remote: tuple[str, int] | None = ...) -> None: ...
    def close(self) -> None: ...
    def processors(self) -> None: ...

    @property
    def remote(self) -> node_info: ...
    @property
    def local(self) -> node_info: ...
    @property
    def timeouts(self) -> connection_timeouts: ...
    @property
    def transport(self) -> str: ...
    @property
    def protocol(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def _in(self) -> connection_stats: ...
    @property
    def _out(self) -> connection_stats: ...

def connection_new(type: str) -> connection: ...

class incident:
    """Incident for reporting events."""

    def __init__(self, origin: str | None = None) -> None: ...
    def dump(self) -> None: ...
    def keys(self) -> list[bytes]: ...
    def set(self, key: str, value: Any) -> None: ...
    def get(self, key: str) -> Any: ...
    def __setattr__(self, key: str, value: Any) -> None: ...
    def __getattr__(self, key: str) -> Any: ...
    def report(self) -> None: ...

    @property
    def origin(self) -> str: ...

    # Common incident attributes (dynamically set)
    con: connection
    url: str | bytes
    md5hash: str
    path: str
    username: str
    password: str
    status: str
    cmd: bytes | str

class ihandler:
    """Incident handler base class."""

    def __init__(self, pattern: str) -> None: ...
    def apply_config(self, config: dict[str, Any] | None) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def register(self) -> None: ...
    def unregister(self) -> None: ...
    def handle_incident(self, icd: incident, /) -> None: ...

def init_traceables() -> None: ...

def dlhfn(name: str, number: int, path: str, line: int, msg: str) -> None:
    """Log handler function for dionaea logging."""
    ...

# Connection error constants
ECONDNSTIMEOUT: int
ECONUNREACH: int
ECONNOSUCHDOMAIN: int
ECONMANY: int
