# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "connection",
    "connection_accounting",
    "connection_new",
    "connection_speed",
    "connection_stats",
    "connection_timeouts",
    "dionaea",
    "dlhfn",
    "ihandler",
    "incident",
    "node_info",
]

class connection:
    r"""
    Connection object exposed to Python. Protocol handlers subclass this.
    
    Python protocols override `handle_io_in`, `handle_established`, etc.
    Rust calls these callbacks when I/O events occur.
    
    The I/O task owns the receiver end of the send channel.
    Python's `send()` pushes data through the sender.
    """
    @property
    def transport(self) -> builtins.str:
        r"""
        Transport type as a string ("tcp", "tls", "udp").
        """
    @property
    def protocol(self) -> builtins.str:
        r"""
        Protocol name (set by Python, e.g. "smbd", "httpd").
        """
    @property
    def status(self) -> builtins.str:
        r"""
        Connection state as a string.
        """
    @property
    def remote(self) -> node_info:
        r"""
        Remote endpoint address info.
        """
    @property
    def local(self) -> node_info:
        r"""
        Local endpoint address info.
        """
    @property
    def timeouts(self) -> connection_timeouts:
        r"""
        Connection timeout configuration.
        """
    @property
    def _in(self) -> connection_stats:
        r"""
        Ingress connection stats.
        """
    @property
    def _out(self) -> connection_stats:
        r"""
        Egress connection stats.
        """
    def __new__(cls, proto: typing.Optional[builtins.str] = None, *_args: typing.Any, **_kwargs: typing.Any) -> connection:
        r"""
        Construct the Rust struct. Python subclasses call __init__ via super().
        """
    def __init__(self, proto: typing.Optional[builtins.str] = None) -> None:
        r"""
        Initialize the connection. Called after __new__.
        Python subclasses call `super().__init__(proto)` which reaches here.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Hash by connection ID. Required for storing connections in Python dicts/sets.
        """
    def __richcmp__(self, other: typing.Any, op: int) -> builtins.bool:
        r"""
        Compare connections by ID.
        """
    def apply_config(self, _config: typing.Any) -> None:
        r"""
        Apply configuration dict. Override in Python subclasses.
        """
    def apply_parent_config(self, slf: connection, parent: typing.Any) -> None:
        r"""
        Copy shared config values from parent connection.
        
        Iterates `parent.shared_config_values` and copies each named attribute
        from parent to self. Matches the C `connection_apply_parent_config`.
        """
    def send(self, data: typing.Any, local: typing.Optional[tuple[builtins.str, builtins.int]] = None, remote: typing.Optional[tuple[builtins.str, builtins.int]] = None) -> None:
        r"""
        Send data to the remote peer.
        
        For UDP, `local` and `remote` specify the source and destination addresses.
        """
    def bind(self, addr: builtins.str, port: builtins.int, iface: builtins.str = ...) -> builtins.int:
        r"""
        Bind the connection to a local address and port.
        """
    def listen(self, size: builtins.int = ...) -> builtins.int:
        r"""
        Listen for incoming connections. Starts the listener task.
        
        Requires `bind()` to be called first to set the local address.
        Uses the global runtime state for registry, limits, and listener tracking.
        """
    def connect(self, addr: builtins.str, port: builtins.int, iface: builtins.str = ...) -> None:
        r"""
        Initiate an outbound TCP connection. Fire-and-forget: returns immediately,
        calls `handle_established` on success or `handle_error` on failure.
        """
    def close(self) -> None:
        r"""
        Close this connection.
        """
    def start_tls(self) -> None:
        r"""
        Upgrade this TCP connection to TLS (STARTTLS pattern).
        
        The I/O task flushes pending writes, then performs a TLS handshake
        using the listener's SSL acceptor. After the handshake, data flows
        over TLS transparently.
        """
    def processors(self) -> None:
        r"""
        Attach the processor pipeline to this connection.
        """
    def ref(self) -> builtins.int:
        r"""
        Increment reference count.
        """
    def unref(self) -> builtins.int:
        r"""
        Decrement reference count.
        """
    def handle_established(self) -> None:
        r"""
        Called when connection is established. Override in Python.
        """
    def handle_io_in(self, data: bytes) -> builtins.int:
        r"""
        Called when data arrives. Override in Python.
        Returns number of bytes consumed.
        """
    def handle_io_out(self) -> None:
        r"""
        Called when the outbound buffer is flushed. Override in Python.
        """
    def handle_disconnect(self) -> builtins.bool:
        r"""
        Called on disconnect. Return true to reconnect (outbound only).
        """
    def handle_error(self, err: typing.Any) -> None:
        r"""
        Called on error. Override in Python.
        """
    def handle_timeout_idle(self) -> builtins.bool:
        r"""
        Called on idle timeout. Return true to keep alive.
        """
    def handle_timeout_sustain(self) -> builtins.bool:
        r"""
        Called on sustain timeout. Return true to keep alive.
        """
    def handle_timeout_listen(self) -> builtins.bool:
        r"""
        Called on listen timeout. Return true to keep alive.
        """
    def handle_origin(self, parent: typing.Any) -> None:
        r"""
        Called to set parent connection context.
        """

@typing.final
class connection_accounting:
    r"""
    Byte accounting for one direction.
    """
    @property
    def bytes(self) -> builtins.float:
        r"""
        Bytes transferred so far.
        """
    @property
    def limit(self) -> builtins.float:
        r"""
        Byte limit (0 = unlimited).
        """
    @limit.setter
    def limit(self, value: builtins.float) -> None: ...

@typing.final
class connection_speed:
    r"""
    Speed (throughput) statistics for one direction.
    """
    @property
    def bps(self) -> builtins.float:
        r"""
        Current speed in bytes per second.
        """
    @property
    def limit(self) -> builtins.float:
        r"""
        Speed limit in bytes per second (0 = unlimited).
        """
    @limit.setter
    def limit(self, value: builtins.float) -> None: ...

@typing.final
class connection_stats:
    r"""
    Combined stats for one direction (speed + accounting).
    """
    @property
    def speed(self) -> connection_speed:
        r"""
        Speed statistics for this direction.
        """
    @property
    def accounting(self) -> connection_accounting:
        r"""
        Accounting statistics for this direction.
        """

@typing.final
class connection_timeouts:
    r"""
    Connection timeout configuration exposed to Python.
    
    All values are in seconds (f64).
    Read/write: gets snapshot from metadata, writes send control messages through the channel.
    """
    @property
    def idle(self) -> builtins.float:
        r"""
        Idle timeout for established connections.
        """
    @idle.setter
    def idle(self, value: builtins.float) -> None: ...
    @property
    def sustain(self) -> builtins.float:
        r"""
        Sustain (session) timeout.
        """
    @sustain.setter
    def sustain(self, value: builtins.float) -> None: ...
    @property
    def listen(self) -> builtins.float:
        r"""
        Listen timeout.
        """
    @listen.setter
    def listen(self, value: builtins.float) -> None: ...
    @property
    def handshake(self) -> builtins.float:
        r"""
        TLS handshake timeout.
        """
    @handshake.setter
    def handshake(self, value: builtins.float) -> None: ...
    @property
    def connecting(self) -> builtins.float:
        r"""
        Outbound connect timeout.
        """
    @connecting.setter
    def connecting(self, value: builtins.float) -> None: ...
    @property
    def reconnect(self) -> builtins.float:
        r"""
        Reconnect delay timeout.
        """
    @reconnect.setter
    def reconnect(self, value: builtins.float) -> None: ...
    def __new__(cls) -> connection_timeouts:
        r"""
        Create timeouts with default values.
        """

@typing.final
class dionaea:
    r"""
    Global dionaea singleton exposed to Python.
    
    Provides access to config, interface addresses, and version information.
    """
    def config(self) -> dict:
        r"""
        Return the parsed configuration as a Python dict.
        
        Builds the flat-dotted-key dict format matching the C module.c output:
        ```python
        {
            "dionaea": {"listen.mode": "...", "listen.addresses": [...], ...},
            "module": {"service_configs": [...], "ihandler_configs": [...]},
        }
        ```
        """
    def getifaddrs(self) -> dict:
        r"""
        Return network interface addresses.
        
        Returns a dict matching the C module.c format:
        ```python
        {"en0": {2: [{"addr": "192.168.1.1"}], 10: [{"addr": "fe80::1"}]}}
        ```
        Keys: interface name → AF number (2=AF_INET, 10=AF_INET6) → list of addr dicts.
        """
    def version(self) -> builtins.str:
        r"""
        Return the dionaea version string.
        """

class ihandler:
    r"""
    Incident handler exposed to Python.
    
    Python ihandler subclasses (logsql, hpfeeds, log_json, etc.) define methods like
    `handle_incident_dionaea_connection_tcp_accept(self, incident)`. The dispatch
    logic replaces dots with underscores and looks for a specific method first,
    falling back to `handle_incident(incident)`.
    """
    @property
    def pattern(self) -> builtins.str:
        r"""
        The glob pattern this handler matches.
        """
    def __new__(cls, *_args: typing.Any, **_kwargs: typing.Any) -> ihandler:
        r"""
        Accept any args/kwargs from Python subclass constructors.
        The actual pattern is set in `__init__`.
        """
    def __init__(self, pattern: typing.Optional[builtins.str] = None) -> None:
        r"""
        Initialize the handler. Python subclasses call `super().__init__(pattern)`.
        
        Auto-registers this handler in the global IHandlerRegistry if the runtime
        is initialized. Matches the C behavior where `ihandler.__init__()` calls
        `c_ihandler_new()` to register immediately.
        """
    def apply_config(self, _config: typing.Any) -> None:
        r"""
        Apply configuration dict to this handler.
        """
    def start(self) -> None:
        r"""
        Start the handler. Called after all handlers are registered.
        """
    def stop(self) -> None:
        r"""
        Stop the handler. Called during shutdown.
        """
    def register(self) -> None:
        r"""
        Register this handler with the incident system.
        """
    def unregister(self) -> None:
        r"""
        Unregister this handler from the incident system.
        """
    def handle_incident(self, _incident: typing.Any) -> None:
        r"""
        Default incident handler. Override in Python subclasses.
        """

class incident:
    r"""
    Incident exposed to Python protocol handlers and ihandlers.
    
    Dynamic attributes are stored in a `HashMap<String, OpaqueData>` and accessed
    via `__getattr__`/`__setattr__`. The `origin` property is read-only.
    
    Connection objects are also stored as `Py<PyAny>` in `py_refs` so that Python
    handlers get back the original object (with .protocol, .transport, etc.)
    instead of a bare connection ID integer.
    """
    @property
    def origin(self) -> builtins.str:
        r"""
        The incident origin path (e.g. "dionaea.connection.tcp.accept").
        """
    def __new__(cls, origin: typing.Optional[builtins.str] = None) -> incident:
        r"""
        Create an incident with an optional origin path.
        """
    def report(self) -> None:
        r"""
        Report this incident to all matching handlers in the registry.
        
        Locks the registry to find matching handlers, releases the lock,
        then dispatches to each handler. This ordering prevents deadlocks
        when a handler callback reports another incident.
        
        Dispatch is serialized across threads to match the C single-threaded
        model. Python handlers (e.g. logsql) share mutable state (sqlite3
        cursors) that isn't thread-safe, and sqlite3 releases the GIL during
        cursor.execute(), which would allow concurrent dispatch without this
        serialization.
        
        Errors in individual handlers are logged but not propagated,
        matching the C behavior.
        """
    def keys(self) -> builtins.list[bytes]:
        r"""
        List all data keys as bytes, matching C behavior where keys are `char *`.
        """
    def set(self, key: builtins.str, value: typing.Any) -> None:
        r"""
        Set a data field by key.
        """
    def get(self, key: builtins.str) -> typing.Any:
        r"""
        Get a data field by key.
        """
    def __getattr__(self, name: builtins.str) -> typing.Any:
        r"""
        Dynamic attribute access: `incident.con`, `incident.port`, etc.
        
        Returns the original Python object for connection-type attributes,
        falling back to OpaqueData conversion for everything else.
        """
    def __setattr__(self, key: builtins.str, value: typing.Any) -> None:
        r"""
        Dynamic attribute setting: `incident.con = value`, etc.
        
        Connection objects are stored as both OpaqueData (for Rust handlers)
        and as the original Python object (for Python handlers).
        """
    def dump(self) -> None:
        r"""
        Dump incident contents (for debugging).
        """

@typing.final
class node_info:
    r"""
    Network endpoint address exposed to Python protocol handlers.
    
    The `host` and `port` properties are read-write; `hostname` is read-only.
    """
    @property
    def host(self) -> builtins.str:
        r"""
        The node's address as a string.
        """
    @host.setter
    def host(self, value: builtins.str) -> None: ...
    @property
    def hostname(self) -> builtins.str:
        r"""
        The node's hostname (empty string if unset, matching C behavior).
        """
    @property
    def port(self) -> builtins.int:
        r"""
        The node's port in host byte order.
        """
    @port.setter
    def port(self, value: builtins.int) -> None: ...
    def __new__(cls) -> node_info:
        r"""
        Create a node info defaulting to 0.0.0.0:0.
        """

def connection_new(con_type: builtins.str) -> typing.Any:
    r"""
    Factory function for creating connections from Python.
    """

def dlhfn(name: builtins.str, number: builtins.int, path: builtins.str, line: builtins.int, msg: builtins.str) -> None:
    r"""
    Bridge Python logging to Rust tracing.
    
    Called by `dionaea/log.py` as `dlhfn(name, number, path, line, msg)`.
    Level mapping: TRACE(5)→trace, DEBUG(10)→debug, INFO(20)→info,
    WARNING(30)→warn, ERROR(40)→error, CRITICAL(50)→error, <10→trace.
    """

g_dionaea: dionaea
