[project]
name = "dionaea"
dependencies = [
    "construct>=2.10.0",
]

[tool.tox]
legacy_tox_ini = """
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

[tox]
envlist =
    lint
skip_missing_interpreters = true

[testenv:lint]
deps =
    ruff
    mypy
skip_install = true
commands = ruff check {toxinidir}/modules
           mypy --no-strict-optional --ignore-missing-imports --allow-untyped-globals \
               --disable-error-code=import-untyped \
               --exclude 'modules/python/dionaea/(submit_http|hpfeeds|virustotal|s3)\\.py' \
               --exclude 'modules/python/dionaea/(mqtt|pptp|sip|memcache|mongo)/' \
               --exclude 'modules/python/dionaea/tftp\\.py' \
               --exclude 'modules/python/util/(csv2sqlite|xmpp/pg_backend)\\.py' \
               {toxinidir}/modules

[testenv:integration]
deps =
    -r{toxinidir}/tests/requirements.txt
skip_install = true
passenv =
    DIONAEA_HOST
    DIONAEA_TFTP_PORT
    DIONAEA_FTP_PORT
    DIONAEA_SMB_PORT
    DIONAEA_HTTP_PORT
    DIONAEA_MYSQL_PORT
    DIONAEA_EPMAP_PORT
    DIONAEA_RDP_PORT
commands = pytest {toxinidir}/tests -v --timeout=30 {posargs}
"""
